### ISSUE TITLE
Add rails to project

### ISSUE THREAD

**Issue by pedrombl** [SAJU-UFRGS/coloquio#1]
Add Rails 4 to project and the current html should continue work.
Some tasks:
* Add Rails 4 to project
* Make it work with Heroku -> Change the ```Procfile```

**Comment by glauco** [comment]
@pedrombl I will start doing this one!

Could you please assign it to me?

**Comment by glauco** [comment]
Done!

Check out the pull request: https://github.com/SAJU-UFRGS/coloquio/pull/12
